version: "3"

dotenv: [".env"]

vars:
  PYTHONPATH: "{{.ROOT_DIR}}/src"
  TEST_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@localhost:5433/instructor_test"

tasks:
  dev:
    desc: Start app + db containers, tail logs
    cmds:
      - docker-compose up --build

  dev:down:
    desc: Stop all containers
    cmds:
      - docker-compose down

  dev:rebuild:
    desc: Rebuild app container after dependency changes
    cmds:
      - docker-compose build --no-cache app
      - docker-compose up -d app

  db:migrate:
    desc: Run Alembic migrations against dev DB
    cmds:
      - PYTHONPATH={{.PYTHONPATH}} alembic upgrade head

  db:reset:
    desc: Drop and recreate dev database
    cmds:
      - docker-compose exec db psql -U postgres -c "DROP DATABASE IF EXISTS instructor;"
      - docker-compose exec db psql -U postgres -c "CREATE DATABASE instructor;"
      - task: db:migrate

  test:
    desc: Run all tests (unit + integration)
    cmds:
      - task: test:unit
      - task: test:integration

  test:unit:
    desc: Run unit tests only (no DB needed)
    cmds:
      - PYTHONPATH={{.PYTHONPATH}} pytest src/tests/ -m "not integration and not live" -v

  test:integration:
    desc: Start test DB, run integration tests, stop
    cmds:
      - docker-compose --profile test up -d db-test
      - docker-compose --profile test exec db-test sh -c "until pg_isready -U postgres; do sleep 1; done"
      - defer: docker-compose --profile test stop db-test
      - >-
        PYTHONPATH={{.PYTHONPATH}}
        TEST_DATABASE_URL={{.TEST_DATABASE_URL}}
        pytest src/tests/ -m integration -v

  test:cov:
    desc: Run all tests with coverage report
    cmds:
      - >-
        PYTHONPATH={{.PYTHONPATH}}
        pytest src/tests/ -m "not live"
        --cov=src/instructor --cov-report=term-missing --cov-report=html

  lint:
    desc: Run Ruff linter
    cmds:
      - ruff check src/

  format:
    desc: Run Ruff formatter
    cmds:
      - ruff format src/

  typecheck:
    desc: Run mypy
    cmds:
      - PYTHONPATH={{.PYTHONPATH}} mypy src/instructor/

  check:
    desc: Run lint + typecheck + test (full local CI)
    cmds:
      - task: lint
      - task: typecheck
      - task: test

  ci:
    desc: Mirror GitHub Actions pipeline in Docker
    cmds:
      - docker-compose build app
      - docker-compose run --rm app ruff check src/
      - docker-compose run --rm app mypy src/instructor/
      - docker-compose --profile test up -d db-test
      - docker-compose --profile test exec db-test sh -c "until pg_isready -U postgres; do sleep 1; done"
      - defer: docker-compose --profile test stop db-test
      - >-
        docker-compose run --rm
        -e TEST_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db-test:5432/instructor_test
        app pytest src/tests/ -m "not live" -v
