"""initial schema

Revision ID: b2cb213e6652
Revises: 
Create Date: 2026-02-15 19:27:19.669726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2cb213e6652'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('language', sa.Enum('GREEK', 'LATIN', name='language'), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('expected_response', sa.Text(), nullable=True),
    sa.Column('grammar_concepts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('vocabulary_items', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammar_concepts',
    sa.Column('language', sa.Enum('GREEK', 'LATIN', name='language'), nullable=False),
    sa.Column('category', sa.Enum('MORPHOLOGY', 'SYNTAX', 'PHONOLOGY', 'PROSODY', name='grammarcategory'), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('prerequisite_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'name', name='uq_grammar_name')
    )
    op.create_table('learners',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_entries',
    sa.Column('language', sa.Enum('GREEK', 'LATIN', name='language'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('vocabulary_notes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('grammar_notes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('prerequisite_grammar', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_items',
    sa.Column('language', sa.Enum('GREEK', 'LATIN', name='language'), nullable=False),
    sa.Column('lemma', sa.String(length=200), nullable=False),
    sa.Column('part_of_speech', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PREPOSITION', 'CONJUNCTION', 'PARTICLE', 'PRONOUN', 'INTERJECTION', name='partofspeech'), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('forms', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'lemma', 'part_of_speech', name='uq_vocab_lemma')
    )
    op.create_table('learner_grammar',
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('grammar_concept_id', sa.Uuid(), nullable=False),
    sa.Column('mastery_level', sa.Enum('UNKNOWN', 'INTRODUCED', 'PRACTICING', 'FAMILIAR', 'PROFICIENT', 'MASTERED', name='masterylevel'), nullable=False),
    sa.Column('last_practiced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_practiced', sa.Integer(), nullable=False),
    sa.Column('recent_error_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grammar_concept_id'], ['grammar_concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'grammar_concept_id', name='uq_learner_grammar')
    )
    op.create_index(op.f('ix_learner_grammar_grammar_concept_id'), 'learner_grammar', ['grammar_concept_id'], unique=False)
    op.create_index(op.f('ix_learner_grammar_learner_id'), 'learner_grammar', ['learner_id'], unique=False)
    op.create_index('ix_learner_grammar_mastery', 'learner_grammar', ['learner_id', 'mastery_level'], unique=False)
    op.create_table('learner_language_states',
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.Enum('GREEK', 'LATIN', name='language'), nullable=False),
    sa.Column('reading_level', sa.Float(), nullable=False),
    sa.Column('writing_level', sa.Float(), nullable=False),
    sa.Column('listening_level', sa.Float(), nullable=False),
    sa.Column('speaking_level', sa.Float(), nullable=False),
    sa.Column('active_vocabulary_size', sa.Integer(), nullable=False),
    sa.Column('grammar_concepts_mastered', sa.Integer(), nullable=False),
    sa.Column('current_unit', sa.String(length=100), nullable=True),
    sa.Column('last_session_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'language', name='uq_learner_language')
    )
    op.create_index(op.f('ix_learner_language_states_learner_id'), 'learner_language_states', ['learner_id'], unique=False)
    op.create_table('learner_vocabulary',
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('vocabulary_item_id', sa.Uuid(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('repetition_count', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('times_incorrect', sa.Integer(), nullable=False),
    sa.Column('knows_definition', sa.Boolean(), nullable=False),
    sa.Column('knows_forms', sa.Boolean(), nullable=False),
    sa.Column('knows_usage', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_item_id'], ['vocabulary_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'vocabulary_item_id', name='uq_learner_vocab')
    )
    op.create_index('ix_learner_vocab_next_review', 'learner_vocabulary', ['next_review'], unique=False)
    op.create_index('ix_learner_vocab_strength', 'learner_vocabulary', ['learner_id', 'strength'], unique=False)
    op.create_index(op.f('ix_learner_vocabulary_learner_id'), 'learner_vocabulary', ['learner_id'], unique=False)
    op.create_index(op.f('ix_learner_vocabulary_vocabulary_item_id'), 'learner_vocabulary', ['vocabulary_item_id'], unique=False)
    op.create_table('sessions',
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.Enum('GREEK', 'LATIN', name='language'), nullable=False),
    sa.Column('session_type', sa.Enum('LESSON', 'PRACTICE', 'EVALUATION', 'PLACEMENT', name='sessiontype'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performance_summary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_learner_id'), 'sessions', ['learner_id'], unique=False)
    op.create_index('ix_sessions_learner_lang', 'sessions', ['learner_id', 'language', 'started_at'], unique=False)
    op.create_table('session_activities',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('score', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_activities_session_id'), 'session_activities', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_activities_session_id'), table_name='session_activities')
    op.drop_table('session_activities')
    op.drop_index('ix_sessions_learner_lang', table_name='sessions')
    op.drop_index(op.f('ix_sessions_learner_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_learner_vocabulary_vocabulary_item_id'), table_name='learner_vocabulary')
    op.drop_index(op.f('ix_learner_vocabulary_learner_id'), table_name='learner_vocabulary')
    op.drop_index('ix_learner_vocab_strength', table_name='learner_vocabulary')
    op.drop_index('ix_learner_vocab_next_review', table_name='learner_vocabulary')
    op.drop_table('learner_vocabulary')
    op.drop_index(op.f('ix_learner_language_states_learner_id'), table_name='learner_language_states')
    op.drop_table('learner_language_states')
    op.drop_index('ix_learner_grammar_mastery', table_name='learner_grammar')
    op.drop_index(op.f('ix_learner_grammar_learner_id'), table_name='learner_grammar')
    op.drop_index(op.f('ix_learner_grammar_grammar_concept_id'), table_name='learner_grammar')
    op.drop_table('learner_grammar')
    op.drop_table('vocabulary_items')
    op.drop_table('text_entries')
    op.drop_table('learners')
    op.drop_table('grammar_concepts')
    op.drop_table('exercises')
    # ### end Alembic commands ###
